### PR TITLE
Alternative StackItem approach

### PR DESCRIPTION
**Pull request by csmuller**
Hey @nimmortal

Having a separate class for the stack is a great idea.
I took your approach and reworked it. There was a bit of an issue with the Item types. E.g. if you had an instance of the `MapItem` you could still call the `getAsString()` method but then just get null back. I though it would be nicer if the user was restricted to the methods that the item type can really handle. That's why I for example moved the `getAsString()`, `getAsNumber()` and `getAsAddress()` to the new `ByteArrayStack` class, because they are specific for that one.
Once a `StackItem` is deserialized it is already of the right type (`ArrayStackitem`, `MapStackItem` etc.) and the dev can cast the base type to what he expects and work with the given class methods.

I know this description is a bit vague. I hope it makes sense.
Please take a look at my changes and let me know what you think.

### CODE REVIEW

**Comment by nimmortal** [comment]
@claudemiller good job, I think this is more pleasant work flow. I accept your PR, however I currently cannot test it out our server, because we are short of time and need to make things done.

**Comment by nimmortal** [comment]
@claudemiller I have now using your new API implementation and can say that it is a bit uncomfortable due to this casts. Maybe we can add static methods to all StackItem implementations? Because now I have quire unreadable code.

`.setStartPrice(((IntegerStackItem) args.get("start_price")).getValue().longValue())` 

I assume that this is more readable

`.setStartPrice((IntegerStackItem.from(args.get("start_price"))).getValue().longValue())`

**Comment by nimmortal** [comment]
Also I found issue in your solution. When I use IntegerStackItem and parameter value is '' (this is zero from neo) then error occurred. Although ByteArrayStackItem is working right.

**Comment by csmuller** [comment]
Sorry for the late response. The `IntegerStackItem.from()` approach is indeed much nicer. We should do that.

There might be other bugs, I didn't thoroughly check the solution yet.
We can continue work directly on your pull-request to neow3j.

**Pull request merged**
